### ISSUE TITLE
第200多行这样改可以根据群昵称确定q号

### ISSUE THREAD

**Issue by litengteng316** [kosakarin/I_have_a_friend#1]
group_member_info = await bot.get_group_member_list(group_id=gid)
        flag=True
        for gm in group_member_info:
            if (gm['card'] and gm['card']==name) or gm['nickname']==name:
                uid=gm['user_id']
                flag=False
                break
        if flag:
            uid = await get_group_member_id(bot, gid, sex)

**Comment by kosakarin** [comment]
这个方法我知道，但是有个问题就是如果用这种方法的话，需要手输的文本必须完全和对方的名字一样（虽然记得qq可以直接复制对方昵称），有些生僻字符的话可能会存在编码的问题（我遇到过，栞字经过cq传入后变成了刊导致没匹配上，没仔细研究怎么处理），所以我打算研究下用类似于前一个触发器的@对方方法实现，回头我封装几个判断方法做个模式选择吧
