### ISSUE TITLE
当内容长度过短时聊天框过长

### ISSUE THREAD

**Issue by SanaChitose** [kosakarin/I_have_a_friend#4]
![图片](https://user-images.githubusercontent.com/102790983/169675016-2cdc1277-c104-4736-ae96-b24e1f0b6e06.png)
显得比较失真，是否可以通过缩短png素材的默认长度来优化？

**Comment by kosakarin** [comment]
应该是可以的，不过需要重新修改图片生成的算法，我摸了挺久🐟有空看看这的算法能不能改一下

**Comment by kosakarin** [comment]
已适配

**Comment by SanaChitose** [comment]
感谢
